### ISSUE TITLE
Beta Test 3 improvements

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#100]
Please do work for this task in a branch called issue-100.

Based upon Beta Test 3, we recommend the following improvements:

ICE Page
* Get to 100: don't include semesters in listing.
* Don't show bottom digit in large ICE icons, just show earned like dashboard.
* Change "Planned" to "Not Earned" and just show not yet earned points.

RadGrad Community Activity widget:
* Show items in reverse chronological order.

 User Explorer Widget:
*  Left justify courses/opportunities in the User Profile
*  Don't show semesters for opportunities, just list them without duplicates

Admin Mode/Opportunity Instance Data Model widget:
* Please sort the drop-down menu entries. 
* Please make ICE point values optional, and if not supplied, default them to their parent Opportunity's values.
* Don't allow duplicate Instances to be created.

Admin Mode/Course Instance Data Model widget:
* Please sort the drop-down menu entries.
* Don't display ICE values, compute them from the grade.
* List courses using their number field, not the short name field.
* Credit hours should not be listed, should be computed from course instance.
* Don't allow duplicate instances to be created.

Course reviews:
* Should be in reverse chronological order
* Rating should display all 5 possibilities in the popup.

**Comment by amymalia** [comment]
Also: Made "note" field in course instances in data model optional. If not given, it defaults to the course number (i.e. ICS 101)
