### ISSUE TITLE
Beta Test Degree Plan Generation improvements

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#101]
Please do work for this task in a branch called issue-101.

Based on beta test experiences, the degree plan generator generates opportunities that need to be almost totally removed.  At this point, it seems to make more sense to either:

a. Do not generate any opportunities and let the student and advisor fill them in;
b. Generate only "minimal" opportunities: for example, ACM Manoa and WetWareWednesday in all Spring and Fall semesters.  

Then, after conversation with the student, more opportunities (i.e. for summer, etc.) can be added to bring them up to 100 I and E.

**Comment by cammoore** [comment]
need to figure out which four academic years to show and the hasPrev and hasNext helpers.

**Comment by cammoore** [comment]
Plan generator adds ACM Manoa, WetWare Wednesdays to student's plans. Also adds greyhats if the student has the 'Security' interest.
