### ISSUE TITLE
Remove extraneous academic years from degree planner

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#109]
Please do work for this task in a branch called issue-109.

Provide a way to delete extraneous academic years:

<img width="1001" alt="screen shot 2017-03-31 at 1 18 47 pm" src="https://cloud.githubusercontent.com/assets/290288/24572476/bc213084-1614-11e7-960d-6f9da3b032fa.png">

**Comment by cammoore** [comment]
Fixed in issue 101
