### ISSUE TITLE
Represent focus areas

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#113]
Please do work for this task in a branch called issue-113.

In addition to degrees (B.A., B.S.), it will be helpful to both students and advisors if focus requirements can be explicitly represented. This involves:

* Students can select any number of focus areas in addition to their degree.
* Focus areas have "implementation dates" (probably indicated by a semester, such as Fall-2017). This enables RadGrad to track changes to focus area requirements. 
* When setting up a student, an advisor can specify the semester the student declared themselves as an ICS major, such as Fall-2016.
* Students can select any version with an implementation date after the semester they declared themselves as an ICS major, as well as the version in effect at the time they declared themselves. 

It should be "cheap" to implement focus areas. Representation of focus areas might consist of just the set of courses that must be taken to satisfy the focus area.

**Comment by cammoore** [comment]
Adding AcademicPlans in addition to the focus areas.

**Comment by cammoore** [comment]
Have Academic Plans. 

* Need a way of declaring which plan the student is following.
* Need to update FeedbackFunctions to use the AP.

**Comment by cammoore** [comment]
Advisor can now choose the plan the student is following.

**Comment by cammoore** [comment]
Feedback functions now use the AcademicPlans.
