### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#119]
[Typescript](https://www.typescriptlang.org/) appears to be the de facto standard for typed JS, and moving to it in RadGrad should:

  1. Reduce the number of currently hidden type-related errors present in our codebase.
  2. Enable us to catch type-related errors at compile time, speeding up development.
  3. Provide type-level documentation about the code, making maintenance and developer on-boarding easier.

The costs are:

  1. We have to spend time to learn Typescript.
  2. We have to spend time to convert our current codebase. 

Given that one thing I wanted to do this summer is a walkthrough of the codebase, it occurs to me that we could combine the two activities by having each of use read some one else's code, and at the same time convert it to Typescript.

Here are some helpful resources to get started:

  * [Typescript](https://www.typescriptlang.org/)
  * [Typescript section of Meteor Guide](https://guide.meteor.com/build-tool.html#typescript)
  * [Example Meteor App using Blaze and Typescript](https://github.com/birkskyum/meteor-typescript-samples/tree/master/blaze)
  * [Five part series on Typescript in Meteor](https://medium.com/@birkskyum/modern-meteor-development-with-typescript-introduction-836f2a89f79)

If this seems like a good idea, I would create a branch to do an initial setup of Typescript and convert some code to complete this issue. Then we can create further issues to migrate the remainder of the codebase.

**Comment by cammoore** [comment]
See [RadGrad2](https://github.com/radgrad/radgrad2).
