### ISSUE TITLE
Implement usage analytics

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#120]
Do work for this issue in a branch called issue-120.

Implement logging to support analytics about user interaction with RadGrad
* When a user logs in (or retrieves home page).
* When a user navigates to a different page. 
* When a interest/career goal is added or deleted, or other interesting interactions with system.

We also need some kind of reporting system and/or export of data to an external tool. 

Should this be dumped separately from rest of DB? 
Are there standard log outputs we should know about that simplify analysis? 
Are there standard Meteor/Mongo logging packages we should leverage?

How do we manage the size of this collection when it gets large? (Maybe that's for a subsequent update because I don't think it will be an issue for the fall. No one subscribes to this collection!  

Admin has method to dump (and maybe clear) the collection. All analysis occurs offline.

Could have a LogStats collection that provides descriptive statistics about contents of log file. Admin can subscribe to that without it getting too big. We could even have an Admin page that just displays this stuff.

**Comment by cammoore** [comment]
Done for now. May look into performance issues with large collection.
