### ISSUE TITLE
Update/fix test fixture.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad#122]
Please do this work in branch issue-122.

Loading the current test fixture takes too long since we are just loading the default database.
We don't need all the students, just abi, betty, charley and alfred.
This will reduce the number of course and opportunity instances, etc.

**Comment by philipmjohnson** [comment]
Fixed in https://github.com/radgrad/radgrad/commit/8e0924cd026828a2f39ed0da8ab5f8d5ab06a009
