### ISSUE TITLE
Fix 'Element is no longer attached to DOM' error

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#127]
Please do work for this task in a branch called issue-127.

Accordions are now showing this error:

![screen shot 2017-06-04 at 10 12 17 am](https://cloud.githubusercontent.com/assets/290288/26765017/7a145d38-490e-11e7-8be8-171f6ea5588d.png)

It appears to be a problem in our Semantic UI theme.  See [this StackOverflow issue](https://stackoverflow.com/questions/37009854/semantic-ui-transition-not-working-in-meteor-1-3) for an approach to resolving it. (Or maybe there's a different way.)

**Comment by cammoore** [comment]
I can't reproduce this error. Is this still a bug?

**Comment by philipmjohnson** [comment]
I can't reproduce it either, so I guess it resolved itself.
