### ISSUE TITLE
Ensure that AcademicPlans are loaded with their associated User on dump/restore

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#129]
Please do work for this task in a branch called issue-129.

I am working on updating the User class, and I am wondering if dump/restore works correctly for AcademicPlans. It seems that the User class has an academicPlanID field, but this field is not written out during dumpOne().  Nor can an AcademicPlan be passed into the User.define() method.   I checked the AcademicPlan.dumpOne() method and it (naturally) does not refer to users.  So it seems that after a dump/restore, users will no longer be associated with their academic plans.

I looked at RadGrad.collectionLoadSequence, and AcademicPlans are loaded after Users.  So, currently, you can’t pass an AcademicPlan into Users.define() because they aren’t defined yet.

Perhaps I’m missing something, and AcademicPlans get hooked up with users some other way, but if not, then I think the way forward is:

1. First, fix AcademicPlans to make their structure consistent with other slug-enabled collections:

  * inherit from BaseSlugCollection
  * AcademicPlans.define() should accept a field called ‘slug’, not ‘degreeSlug’, 
  * AcademicPlans collection should have a field called slugID, not degreeID.

2. Load AcademicPlans before Users. (Change RadGrad.collectionLoadSequence).

3. Fix Users.dumpOne to write out the slug of the academicPlan associated with the user.

4. Fix Users.define to accept an academicPlan (i.e. its slug).

5. Check that Users get restored with their associated Academic Plan.

Let's not start on this issue until we finish updating all collections to use methods.

**Comment by cammoore** [comment]
1. Left in the degreeSlug since an AcademicPlan should satisfy a DesiredDegree.
    Added in a slug that is somewhat like the desired degree slug but adds the year and 'focus'
       (e.g. bs-cs-ss-2017 or ba-ics-it-2015).
2. Moved AcademicPlan to after DesiredDegrees, before ValidUserAccounts.
3. Users.dumpOne now has academicPlan
4. Users.define takes an optional academicPlan slug.
5. Updated fixture for abi to include her AcademicPlan, works.

Waiting to merge into master.

**Comment by cammoore** [comment]
Merged into master.
