### ISSUE TITLE
Show status of verification for Opportunity Instances in Student degree planner

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#132]
Please do work for this task in a branch called issue-132.

Currently, the inspector for a student does not seem to show if an opportunity listed in their degree plan has actually been verified.

So, there are two UI tasks:

1. (Easy) State status of verification in inspector window for all Opportunity Instances. 
2. (Harder) Unobtrusively indicate status of verification in Degree Plan table. One idea: if the Opportunity Instance is in a past semester and has not been verified, then add a tiny icon (question mark?) along with a tool tip that says "This opportunity has not been verified" when the user moves the mouse over it.

**Comment by philipmjohnson** [comment]
Event verification page fixed.

**Comment by cammoore** [comment]
Add Warnings for OpportunityInstances that have not been verified and are in the past.

**Comment by cammoore** [comment]
Turns out that the fixture database was missing VerificationRequests for abi. She had verified OpportunityInstances, but no VerificationRequests for them. I added them to the fixture and now we can see the Request Status.

**Comment by cammoore** [comment]
Fixed bug with requesting verification.
