### ISSUE TITLE
Degree plan warning message has incorrect URL for courses

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#134]
Please do work for this task in a branch called issue-134.

The warning message includes a link to an incorrect URL. For example:

http://localhost:3000/student/markrc/explorer/courses/ics_211-1

Here's a screen shot:
![screen shot 2017-06-28 at 10 51 51 am](https://user-images.githubusercontent.com/290288/27659676-1566e8ca-5bf0-11e7-9834-e4ff529fa3e3.png)

**Comment by cammoore** [comment]
Bug was in the building of the links from the PlanChoice. Didn't strip off the instance number.
