### ISSUE TITLE
Use Academic Plan selection to determine Desired Degree

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#135]
Please do work for this task in a branch called issue-135.

If I navigate away from the degree planner page after having selected an academic plan, then come back to it, my Academic Plan selection is not displayed:

![screen shot 2017-06-28 at 10 57 50 am](https://user-images.githubusercontent.com/290288/27659865-b8a50f30-5bf0-11e7-960e-1d5314e64601.png)

**Comment by philipmjohnson** [comment]
Currently, "desired degree" and the degree program in an "academic plan" are entirely independent. So it's possible for a student to have a B.A. as a desired degree and show a B.S. in their academic plan. We don't check for that. 

Proposal: 

  1. Eliminate Desired Degree. It is implied by your choice of academic plan. 
  2. Put Academic Plan selection under student control.  It is whatever they've selected most recently in the Degree Planner.

**Comment by cammoore** [comment]
Done

**Comment by cammoore** [comment]
Forgot about the Desired Degree Explorer.

**Comment by cammoore** [comment]
The desired degree explorer allows the Student to choose an AcademicPlan associated with the degree. Also runs FeedbackFunctions when the plan changes.
