### ISSUE TITLE
Display Career Goals as labels in Profile pages.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#138]
Please do work for this task in a branch called issue-138.

Interests are displayed as labels, but Career Goals are displayed as text. That seems inconsistent.  

I propose to display them with the same green color as interests, but use the suitcase icon instead.

Note that Student, Advisor, Mentor, Faculty etc. profile pages are all affected.

![screen shot 2017-06-28 at 11 28 47 am](https://user-images.githubusercontent.com/290288/27661176-12eaab4a-5bf5-11e7-8f60-a75d43f5fa55.png)

**Comment by cammoore** [comment]
There isn't an Advisor AboutMe page.

**Comment by cammoore** [comment]
Fixed
