### ISSUE TITLE
Integrate JSDoc API files into GitBook

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#14]
Hopefully we can just output the JSDoc into a GitBook subdirectory. Alternatively explore JSDoc To Markdown (https://www.npmjs.com/package/jsdoc-to-markdown)

**Comment by philipmjohnson** [comment]
I've got jsdoc-to-markdown working, but the format of the markdown that's inserted into our gitbook isn't the best. Need to create a custom template to clean it up.

**Comment by philipmjohnson** [comment]
I went back and altered the original jsdoc generator to put all the HTML files into a subdirectory in GitBook.  The results are better than jsdoc-to-markdown with the default template, but probably not as good as we could do with a custom template. Check out the JSDocs link in the table of contents for the published GitBook to see.

**Comment by KevinAst** [comment]
Just noticed your issue on Integrating JSDoc API files into GitBook.

I see where you are referencing your JSDoc generated html from your GitBook docs.

**FYI:** You may be interested in my docs site: https://astx-redux-util.js.org/

- I am promoting a very polished set of docs using Gitbook, while still relying on my embedded JSDoc comments for the API.

- The **secret in accomplishing this integration** is to use the [jsdoc-to-markdown](https://www.npmjs.com/package/jsdoc-to-markdown) package to generate the low-level API as Markdown (from the JSDoc comments in your code).  Once this is accomplished, it can be easily integrated into the overall GitBook Markdown structure.

- I have created a **comprehensive [gist](https://gist.github.com/KevinAst/7e12648245ff2a8e9c1557135014b933) that details how I accomplished this**.

I would encourage you to explore this technique further.

Thoughts?

</Kevin>

**Comment by philipmjohnson** [comment]
@KevinAst Wow, that's gorgeous!  Much better than what we're doing.  After the semester is over I am definitely going to try out your approach. Thanks for the comment!

**Comment by KevinAst** [comment]
Hi @philipmjohnson ... I opened [jsdoc-to-markdown issue124](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/124) in an attempt to get some visibility of my [article](https://medium.com/@kevinast/integrate-gitbook-jsdoc-974be8df6fb3).  Unfortunately, they closed it immediately saying they didn't think there was any great demand :-(

I thought if you were so inclined you may want to weigh in!

`</Kevin>`

**Comment by philipmjohnson** [comment]
I spent a couple of hours trying out your approach. It doesn't seem to look as good as docdash on larger code bases.  It also doesn't seem to process certain jsdoc directives properly. Notice in the following screenshot that the `@extends` and `@throws` directives don't format correctly, and in turn the table formatting for parameters is not correct. 

Perhaps I'll fiddle more with this later.   My initial foray is saved in this branch:

https://github.com/radgrad/radgrad/tree/issue-123

**Comment by KevinAst** [comment]
Hi @philipmjohnson,

Yes my project had a very small API, employing a small number of JS features.

- That's too bad about the formatting problems with extends and throws.

- I'm not sure the table formatting problem is visible in your screen print, but I suspect it has something to do with a vertical bar (|) being in the data of your table.

I too am experiencing minor problems (on another project) with things like unlinkable references that have dots (.) in the name.  So far I have been able to find work-around patches, but they are starting to build up.

I was thinking that on a larger project I would need to revise my approach to use multiple api md files.

I was going to ask you what docdash was, but I think you are referring to the JSDoc theme - yes?  That doesn't really address the integration between gitbook/jsdoc - correct?

Thanks for the feedback.

</Kevin>

**Comment by philipmjohnson** [comment]
Yes, I'm just using the jsdoc docdash theme and outputing the raw HTML.
