### ISSUE TITLE
Improve Advisor Student Configuration Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#146]
Please do work for this task in a branch called issue-146.

1. Add a Results read-only text area that can be used to show results of button pushing at the bottom of the page. 
2. Advisor need not select the desired degree or academic plan.  They only specify the declared semester.  (Make sure that student selections in degree planner are saved after selection).
3. Looks like things are not working, but that's the degree/plan stuff which is going to be deleted anyway. 

Add New Student Page has errors:
* If the UH ID field is wrong, no error is reported.
* No logging output to indicate success/failure.

**Comment by cammoore** [comment]
Have updated the add student. No longer asks for UH-ID. 
Sets the declared semester to the current semester.
