### ISSUE TITLE
Make Level computation private

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#147]
Please do work for this task in a branch called issue-147.

Currently, one can simply look at the public source code to figure out the criteria for Level computation. It would be better if this computation were "private".

One could create an object with parameters specifying what's required for Levels, and then put the actual values in a settings file.   It would be even better if we could somehow "inject" the Level computation functions as a settings file.

**Comment by cammoore** [comment]
Have a partial solution. The logic is still hard coded, but the actual values are in the Meteor.settings.public.level object.

**Comment by cammoore** [comment]
Now have a .gitignored file calcLevel.js. It must export a function named calcLevel that takes a studentID. In the settings.development/production.json file uses the following setting:

"level": {
      "use_hidden" : true,
      "six": {"i": 100, "c": 100, "e": 100, "reviews": 6},
      "five": {"i": 80, "c": 80, "e": 80, "reviews": 1},
      "four": {"i": 30, "c": 36, "e": 30, "reviews": 0},
      "three": {"i": 1, "c": 24, "e": 1, "reviews": 0},
      "two": {"i": 0, "c": 12, "e": 0, "reviews": 0}
    }

If use_hidden is false we use the default hard-coded defaultCalcLevel function that is public. if it is true then we'll use the hidden calcLevel function.
