### ISSUE TITLE
Redesign DesiredDegree explorer as AcademicPlan explorer

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#153]
Please do work for this task in a branch called issue-153.

I don't students might be better off if the  "Desired Degree" explorer was now an "Academic Plan" explorer. 

Also, I think the Desired Degree explorer page now has bugs.

**Comment by cammoore** [comment]
Done, but we may need better descriptions of the individual plans. I took the descriptions from the AcademicPlan document, but they are sparse.
