### ISSUE TITLE
Refactor form-fields

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#158]
Please do work for this task in a branch called issue-158.

Currently, templates for encapsulating form fields and their controllers are located in at least two places:
  * ui/components/admin/form-fields
  * ui/components/advisor/form-fields

Some of these have overlapping functionality.

Most form fields (controllers) are generic, not role-specific, so we should indicate that by placing those template definitions in:

  * ui/components/form-fields

And populate it with the role-agnostic form field templates.

**Comment by cammoore** [comment]
I've moved all the form-fields into the components/form-fields directory. Not sure if any of them are role specific. Some are only used by admin data model, but that doesn't mean it is role specific.
