### ISSUE TITLE
Create radgrad.ics.hawaii.edu and deployment scripts

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#16]
- Set up radgrad.ics.hawaii.edu host name.
- Determine how to deploy radgrad to UH virtual hosting.
- Write script to automate deployment 
- Write script to download contents of Mongo database for backup and reinitialization purposes.

Please do work on this task in a branch called issue-16.

**Comment by henricasanova** [comment]
Scripts have been added to the radgrad repo, and are currently used to deploy radgrad on  the radgrad.ics.hawaii.edu ITS VM, as well as other apps. We should be ready to move from Galaxy to in-house deployment whenever.
