### ISSUE TITLE
Recommended Opportunities Widget is busted

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#166]
Please do work for this task in a branch called issue-166.

The "Add to Plan" and "Hide" buttons do not work.

![screen shot 2017-07-22 at 8 49 24 am](https://user-images.githubusercontent.com/290288/28493885-d9c4d7fe-6eba-11e7-959f-7198fac16fa8.png)

**Comment by cammoore** [comment]
One issue is Semesters.getCurrentSemester doesn't return the document, but the ID of the current semester.  Maybe we should change the name of this method to getCurrentSemesterID to make it more clear.

**Comment by cammoore** [comment]
Fixed the problem with hide courses and opportunities. Student explorer career goals and interests fixed.
