### ISSUE TITLE
isAlumni is busted

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#169]
Please do work for this task in a branch called issue-169.

In the updateStudent pane, the isAlumni radio button does not have a selection. If you select True and press update, the student does not become an alumni.

<img width="702" alt="screen shot 2017-07-28 at 7 19 28 am" src="https://user-images.githubusercontent.com/290288/28728708-56105a78-7365-11e7-8319-0f152222df94.png">

**Comment by cammoore** [comment]
Fixed. Need to convert 'true' to true and '3' to 3 for isAlumni and level.
