### ISSUE TITLE
Set up UH CAS login and roles

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#17]
- See https://github.com/ics-software-engineering/meteor-example-uh-cas
- Implement a collection of allowed UH account names and their roles.
- Provide an initialization function.
- Route to role-specific home page on login
- Remove useraccounts:semantic-ui package.

Please do work on this task in a branch called issue-17.

**Comment by cammoore** [comment]
Not quite ready. Still have to deal with the 'fake' students that can't login through CAS.

**Comment by cammoore** [comment]
This issue is OBE. See the meeting notes for 12/1/16.
