### ISSUE TITLE
Font in accordions (MentorSpace) is not Open Sans

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#174]
Please do work for this task in a branch called issue-174.

Probably resolved by editing our custom Semantic UI theme.

**Comment by cammoore** [comment]
This is true in all of our accordions. The site.variables has the lines:
/* Define our fonts. */
@headerFont        : 'Nunito', 'Helvetica Neue', Arial, Helvetica, sans-serif;
@pageFont          : 'Open Sans', 'Helvetica Neue', Arial, Helvetica, sans-serif;

We can easily change the @headerFont

**Comment by cammoore** [comment]
Changed the type of accordion to match the data model accordions. This fixes the font issue.

Awaiting review.
