### ISSUE TITLE
Reduce transparency about courses

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#175]
Please do work for this task in a branch called issue-175.

In public student profile, eliminate listing of courses/opportunities taken and planned.

In descriptions of courses and opportunities, only put student images if they have already completed the course/opportunity.

Take out grades from the degree planner for completed classes.

**Comment by cammoore** [comment]
Not showing students in Course, Opportunity, Academic Plans and Degree explorers.
Removed Courses and Opportunities from Users explorer.
Removed Grades from past courses in Degree Planner.
