### ISSUE TITLE
Do not publish all CourseInstances and all OpportunityInstances

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#176]
Please do work for this task in a branch called issue-176.

Publishing all instances makes the amount of data downloaded proportional to the number of students in the system, which could have a scalability impact. 

If we no longer display students associated with courses and opportunities (issue #175) then we do not need to subscribe to all instances, just those associated with the current student.

**Comment by cammoore** [comment]
Cleaned up some of the publications and subscriptions.
