### ISSUE TITLE
Show planned enrollment for future semesters

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#177]
Please do work for this task in a branch called issue-177.

For future semesters, if we provided students with the number of students who are planning to enroll in a course in each future semester, we can support "crowd-sourcing" of 4xx course offerings by telling students that the more of them who plan to enroll in a course in a specific semester, the more likely we will be able to offer it.

For courses offered every semester, this provides good data on how many sections to offer.

We could display the future semester enrollment data in the Inspector window when you click on a course to see details. 

Each time you move a course to a different semester, that could influence the information shown in the Inspector window.

Implementing this is a little tricky:

  * We don't want to subscribe to all course instances because that has privacy and scalability issues. (400 students x 20 courses = 8K records just to implement this feature).

  * We could have a method that is called with a course and returns a data structure containing future course enrollment data. Each time the Inspector pane is refreshed, we can call the method to get the info. It could happen asynchronously (?)

  * Movement in the degree planner pane should result in an update to the Inspector window. This is the tricky part.  Do we use a reactive var? A local client-side-only collection?

**Comment by cammoore** [comment]
Forgot to add CourseCollection.methods to index.js.

**Comment by cammoore** [comment]
Very basic view in the inspector.
