### ISSUE TITLE
Debug STAR upload mechanism

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#178]
Please do work for this task in a branch called issue-178.

Two issues:

1. Uploading sometimes results in multiple copies of ICS 111 in plan for early semesters.
2. Recalculate Level process is busted (profileID related error in console.)

**Comment by cammoore** [comment]
Fixture data was bogus for the CourseInstances and OpportunityInstances.
 * CIs had verified: true, but were missing fromSTAR: true.
 * OIs had verified: true for future instances. This is impossible.

**Comment by cammoore** [comment]
The problem with one of the STAR data was a Winter semester. I ended up calling it Fall.
