### ISSUE TITLE
Disable restriction on adding Opportunities to prior semesters

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#179]
Please do work for this task in a branch called issue-179.

Currently, the student degree planner does not allow students to add Opportunities to prior semesters. 

In thinking through the roll-out process, we will have many students who want to get ICE points for prior participation in hackathons, clubs, and so forth.  Doing that is currently not possible for advisors, only admins can create Opportunity Instances for prior semesters. 

We could create a new advisor widget to add historical Opportunity Instances for students, but a more simple solution is to just disable the restriction for students on adding Opportunities to semesters in the past.  

The opportunity would still need to be verified, but if that restriction is removed, then it is straightforward for an advisor to help a student fill out their degree plan including historical opportunities and get them verified immediately

**Comment by cammoore** [comment]
Can now drag courses and opportunities into the past. Dragged courses can be removed in the inspector. STAR courses cannot be removed.

* There is a bug in the ICE calculations you get planned C points for dragged courses in the past.
