### ISSUE TITLE
Review implementation

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#186]
Currently, the Analytics framework is based upon a combination of a RadGrad collection (AppLogs) and a third party logger (ostrio:loggermongo). 

Some of the issues with the current implementation include:

* Redundant fields. It appears that the "date" and "timestamp" fields maintain the same info, just in a different format. 

* Unnecessary fields. For analytics, the "Level" field appears to be unnecessary.  

* Unavailable fields. I'm not sure how to get at the "additional" field. All of the invocations just pass the "message" field.

What are the benefits to using the ostrio:loggermongo package?  It appears to be "isomorphic", so we (I guess) don't need to call a Meteor method to add data from the client side. Are there any other benefits? If not, would it be simpler to just use our own collection and create a single Method that we call to add data?  It seems like it automatically logs exceptions (maybe?) which is another capability we don't need for analytics.

On the other hand, providing our own package provides us with easy facilities for dump/restore etc. 

I don't know enough about logging yet to decide whether the logger adds enough value to keep, but now that I get into it I wonder if combining our own collection mechanism with a third party logger is the right way to go. 

Perhaps we can discuss this in the comments?

**Comment by cammoore** [comment]
We might want to take a look at FiLog https://github.com/FGM/filog. Looks like a complete solution and is a npm package.

**Comment by philipmjohnson** [comment]
I'm closing this since we'll move to a custom solution.
