### ISSUE TITLE
Logged In Users

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#187]
Please do work for this task in a branch called issue-187.

Create an analytics widget called "Logged In Users". It should provide a simple list of the users who are currently logged in to the system. 

Here is a third party package that appears to be currently maintained: 

https://github.com/mizzao/meteor-user-status

Here's a blog about an app that uses it which might be helpful:

https://medium.com/@maxpleaner/meteor-tutorial-plotting-online-users-on-a-map-adf3c3d1ebc6

**Comment by cammoore** [comment]
Done
