### ISSUE TITLE
Mockup admin home page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#19]
- See [Use Cases](https://radgrad.gitbooks.io/radgrad-manual/content/use-cases.html) for requirements.
- The primary function of the admin is to manage the data model.  Eventually, we don't want to have to define all of the data model entries in Javascript; we would like to be able to login and do it via a UI. 
- At this point, a useful function of the admin home page is to provide a set of widgets that display all of the data model items.  That means the admin needs to subscribe to everything. Once it can display all of the elements, we can create an editor for each item. 
- Once we can edit items online, we'll need to be able to dump the database in a reloadable fashion. 
- Admin is also able to whitelist users and set their role as student, faculty, mentor, advisor. For now, the admin cannot define another user with the admin role.
- Please do work on this task in a branch called issue-19.

**Comment by cammoore** [comment]
Have the pages to view other pages as different roles.

The CRUD page is just a placeholder.

**Comment by philipmjohnson** [comment]
I've got enough of a mockup going to move into implementation. Will close this issue and create new ones for each element of the data model. That way I get to finish 20 issues rather than 2.
