### ISSUE TITLE
Implicitly create academic years so no gaps exist

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#192]
Please do work for this task in a branch called issue-192.

We've discovered that if students create opportunities in the future, then there may be gaps in the sequence of academic years. This appears to mess up drag-and-drop.

As a workaround, you can manually add a course to a semester in the "missing" AY, which will create the AY, then delete the course.

Longer term, whenever an AY is created, the define method should create enough AY instances so that no gaps exist.

**Comment by cammoore** [comment]
AcademicYearInstances.define now fills in any gaps.
