### ISSUE TITLE
Feed has incorrect text

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#198]
Please do work for this task in a branch called issue-198.

The feed has a template text invocation displayed in it:

<img width="392" alt="screen shot 2017-09-18 at 1 25 22 pm" src="https://user-images.githubusercontent.com/290288/30570250-bfead4b6-9c7b-11e7-93b6-b35623eb5470.png">
.

**Comment by cammoore** [comment]
Fixed the text in the feed.description so that is is valid markdown.
