### ISSUE TITLE
Mockup advisor home page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#20]
- See [Use Cases](https://radgrad.gitbooks.io/radgrad-manual/content/use-cases.html) for requirements. 
- Enable advisor to set up a new student in RadGrad.
- Enable uploading of STAR data into a student account.
- Enable the use of templates to create an initial degree program plan over four years. 
- Enable advisor to switch into a student account.
- Enable advisor to indicate that student has received a laptop sticker for a given level.
- Manage opportunity verification requests.
- Please do work on this task in a branch called issue-20.

**Comment by cammoore** [comment]
Taking over ownership.

**Comment by cammoore** [comment]
Opportunity verification is done.

**Comment by cammoore** [comment]
Does the STAR data have their names?  We currently don't have a place for entering the student's name.

**Comment by cammoore** [comment]
Need to add AdvisorLog collection and a way to display on student's page.

**Comment by philipmjohnson** [comment]
To do:
* Update the advisor home page to support creation as well as retrieval of students. 
* Creation means: provide uh account, first and last name, and UH ID.  This adds that student to the RadGrad whitelist so that they can now login successfully.
* Retrieval means to retrieve via UH account name.  If not found, signal an error.

**Comment by cammoore** [comment]
Done.

**Comment by cammoore** [comment]
Forgot the Degree Plan creator and Admin Log
