### ISSUE TITLE
Add 6xx courses.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#201]
Some undergraduates take our grad level courses. 

Add them in.  Perhaps they should be worth more than 6/10 points? 

The menus for the explorer in the degree planner page need to be expanding to include 6xx.

**Comment by cammoore** [comment]
Added the courses, but this has raised some issues.

* Recommendations for undergraduates should or shouldn't include graduate courses? Our current system of recommendations based upon interest doesn't take into account the course level.
* UI presenting all the courses in the inspector that don't apply to the students' plan.
* Prerequisites in the EE department that starts to add other prerequisites. This can grow out of hand.

Going to close the issue without merging it into master.
