### ISSUE TITLE
Write Importer function for batch STAR data

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#204]
Please do work for this task in a branch called issue-204.

Once we have received the first bulk STAR data, implement the bulk importer.

**Comment by cammoore** [comment]
There is something funny with StudentProfiles. What id am I supposed to pass into setLevel? The userID or the id of the profile or the studentID? I think these three things are all different.

**Comment by cammoore** [comment]
Fixed the issue with StudentProfiles.getID. 

But didn't fix the issue in the other profiles. Perhaps move the getID method from StudentProfiles to BaseProfiles.

**Comment by cammoore** [comment]
Moved StudentProfiles.getID to BaseProfile so it will work with the other profiles.

**Comment by cammoore** [comment]
Done. Use radgrad/scripts/ to download the data from STAR, then upload the JSON file from the advisor page.
