### ISSUE TITLE
Identify alumni during STAR data processing.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#215]
Please do work for this task in a branch called issue-215.

When students graduate, STAR clears their course records. We need a mechanism to ensure that when we update current RadGrad users, we do not clear their course records after they graduate, but rather move them to alumni status. Here is a proposed mechanism:

(1) An admin invokes the [script to download STAR data](https://radgrad.gitbooks.io/radgrad-manual/content/developerguide/star-bulk-download.html).

(2) By default, that script identifies "suspicious" looking STAR data during/after the download. Upon completion, the script prints out the following:  "XXX students processed.  YY potential alumni emails stored in alumni.txt.  Remaining STAR data ready for bulk upload in <file.json>", where <file.json> is the file name specified by the user upon invoking the script.

(3) Perhaps there can be a --no-alumni-check flag to disable the suspicious data checking step, but I'm not sure that's even necessary.

This approach leaves it to the admin to go in and manually transfer students to alumni status. In a later task, we could automate this by uploading the alumni.txt file and having RadGrad do it for us.

**Comment by cammoore** [comment]
Done.  The download-bulk-star-json.js script now filters out 'Alumni' and creates a list of the alumni found in the download file.
