### ISSUE TITLE
Combine multiple level achievements in a day in the feed

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#216]
Please do work for this task in a branch called issue-216.

When we upload lots of new students, we get a long list of "Foo achieved Level 2". It would look better to combine these into a single feed entry ("Joe Smith and 34 others achieved Level 2"):

<img width="353" alt="screen shot 2018-03-09 at 1 57 59 pm" src="https://user-images.githubusercontent.com/290288/37235366-2363a7d6-23a2-11e8-83f9-77a630d7b1e5.png">

**Comment by cammoore** [comment]
Done.

We should conduct a review of the Feed system. It is confusing to me.
