### ISSUE TITLE
Mockup student degree planner page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#22]
- See [Use Cases](https://radgrad.gitbooks.io/radgrad-manual/content/use-cases.html) for requirements. 
- Show available courses and opportunities.
- Show degree plan.
- Enable student to add/subtract courses and opportunities from degree plan.
- Show recommendations and warnings generated from current state of degree plan.
- Please do work on this task in a branch called issue-22.

**Comment by cammoore** [comment]
* Add Inspector, Warnings and Recommendations to the bottom of the page.
* Need a simple prerequisite checker when the student adds/deletes a course instance.

**Comment by cammoore** [comment]
Current version is pretty stable.

**Comment by philipmjohnson** [comment]
Things to do:
* Projected ICE

**Comment by cammoore** [comment]
Now includes Projected ICE. May need to figure out how to change the size of the box.
