### ISSUE TITLE
Redesign course scoreboard layout

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#222]
Please do work for this task in a branch called issue-222.

The course scoreboard would be more useful if the layout was a table where:

* Rows are courses, one for each course in the system, ordered alphabetically.
* Columns are the next 9 semesters.

Each cell in the table is the current number of students who are planning to take that course in that semester. 

Bonus points if clicking on the digit in the cell pops up a modal with the names of the students. 

More bonus points for providing some kind of filtering (ICS vs EE, 1xx to 4xx) as checkboxes

This representation is useful because:

* Reading down a column gives the current information (i.e. what courses are requested for a given semester)
* Reading across a row gives new information (during which semesters is a course in particular demand).

**Comment by cammoore** [comment]
Bonus points

**Comment by cammoore** [comment]
Working on performance

**Comment by cammoore** [comment]
Better performance with smaller simpler templates.
