### ISSUE TITLE
Remove event log

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#224]
Please do work for this task in a branch called issue-224.

The Event Log was great while it lasted, but the UserInteraction collection is what we will use moving forward.  If we delete the Event Log, then:

* At least one bug in the current system will go away.
* There is some redundant logging overhead with UserInteraction that will go away if we remove EventLogs, thus improving performance at least slightly.

While there are some behaviors that EventLog tracks that are not tracked by UserInteraction, we should add them into UserInteraction when and if we decide those behaviors are worth logging.

**Comment by cammoore** [comment]
Done.
