### ISSUE TITLE
Require 100 Planned ICE points to reach level 3?

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#229]
Please do work for this task in a branch called issue-228.

It would be good to incentivize students to fill out their plan, and we can do that by requiring them to reach 100 planned ICE points to reach (say) level 3.

In conjunction with this, it might be good to provide enumerated lists of requirements to reach each level in the User's Level page.  That way it's clearer what they need to do next.

**Comment by cammoore** [comment]
Changed the requirement for planned ice [100, 100, 100] to level 4.
