### ISSUE TITLE
Known moderate severity security vulnerability detected in hoek < 4.2.1

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad#233]
Please do work for this task in a branch called issue-233.

  | radgrad/radgrad
-- | --
Known moderate severity security vulnerability detected in hoek < 4.2.1 defined in package-lock.json.package-lock.json update suggested: hoek ~> 4.2.1. | Known moderate severity security vulnerability detected in hoek < 4.2.1 defined in package-lock.json. | package-lock.json update suggested: hoek ~> 4.2.1.
Known moderate severity security vulnerability detected in hoek < 4.2.1 defined in package-lock.json.
package-lock.json update suggested: hoek ~> 4.2.1.

**Comment by philipmjohnson** [comment]
looks like this is fixed.
