### ISSUE TITLE
Implement card-based browser for interests, opportunities, and career goals

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#245]
Please do work for this task in a branch called issue-245.

During onboarding, we ask students to browse the list of interests, career goals, and opportunities and select those that they find to be appealing. The current interface doesn't make that easy, as students just get a (long) list whose items they must click on individually to get descriptions. 

A potentially better UI might be to provide an alternative, card-based display that provides somewhat more detail about each kind of entitiy. They can click on it to get more info and/or add it to their profile.

**Comment by cammoore** [comment]
Done for the student explorers

**Comment by cammoore** [comment]
Done for all the explorers. There could be a little clean up with some of the buttons.
