### ISSUE TITLE
Update radgrad.ics.hawaii.edu from STAR

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#246]
Get listing of all students currently registered for ICS 211 and ICS 314 from their respective instructors. 

Download list of emails of all students in radgrad.ics.hawaii.edu

Backup radgrad.ics.hawaii.edu

Run the STAR bulk data updater to set up all students.

**Comment by philipmjohnson** [comment]
Do this after labor day to get most current class data plus summer grades.

**Comment by cammoore** [comment]
I've uploaded the new STAR data and turned the 28 alumni into alumni.
