### ISSUE TITLE
Not working: Analytics > Student Summary > Timeline Chart

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#277]
Please do work for this task in a branch called issue-277.

On the deployed version of RadGrad, the Timeline Chart does not appear.  Unfortunately, I do not see an error in either the client console or on the server side (via APM). 

The [documentation](https://www.radgrad.org/docs/analytics-engagement.html) shows that this feature was working at some point.

**Comment by philipmjohnson** [comment]
Looks like Danny is not working on this any longer, so re-assigning to Cam.

**Comment by cammoore** [comment]
Can't reproduce this error.
