### ISSUE TITLE
Address dangling Opportunity Instance reference in Verification Requests.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#280]
Please do work for this task in a branch called issue-280.

Consider the following sequence of behaviors:
1. Student adds an opportunity.
2. Students submits that opportunity for verification.
3. Student deletes that opportunity.
4. Advisor displays verification requests.  At this point, the VR will have empty fields, there will be a console error regarding an unknown Opportunity Instance ID. And buttons won't work.

Solution:  when someone deletes an Opportunity, one most also look to see if there is a VR associated with it and delete that as well. 

There can be a unit test for this sequence of behaviors.

**Comment by cammoore** [comment]
For some reason, I had to increase the timeout for CareerGoals tests.
