### ISSUE TITLE
Clicking user link in RadGrad Community Activity window is broken

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#284]
Please do work for this task in a branch called issue-284.

In the RadGrad Community Activity widget on the student home page, clicking the link associated with a username appearing in that window is broken:

<img width="1350" alt="screen shot 2019-02-26 at 9 57 07 am" src="https://user-images.githubusercontent.com/290288/53442382-46b67980-39ad-11e9-8362-a6c8387ca51c.png">

**Comment by cammoore** [comment]
Removed the link to individual students. This was in conflict with FERPA rules.
