### ISSUE TITLE
Indicate when RadGrad is working.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad#287]
Please do work for this task in a branch called issue-287.

There are several places where RadGrad takes a long time to complete a task, dumping the database, uploading STAR data, etc.

We need a way to indicate that RadGrad is working during this time so the user doesn't press the button again and again.

* [x] Admin Data Model: Load Fixture
* [x] Admin Database: Check Integrity
* [x] Admin Database: Dump Database
* [x] Admin Database: Get Student Emails
* [x] Advisor: Bulk Star Upload
* [x] Advisor: Get Student Emails
* [x] Analytics - Newsletter
* [x] Analytics - Overhead Analysis
* [x] Analytics - Student Summary

**Comment by cammoore** [comment]
Not sure we need the analytics.

**Comment by cammoore** [comment]
Going to close for now.

**Comment by cammoore** [comment]
Need to do overhead and student summary

**Comment by philipmjohnson** [comment]
database backup download button?

**Comment by philipmjohnson** [comment]
My bad, db backup button has the twirly thing now!

**Comment by cammoore** [comment]
I thought so.
