### ISSUE TITLE
mLab upgrade to 3.6

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#297]
Just got the following email from mLab:

Hello from mLab,

We are writing to inform you that we are discontinuing support for MongoDB 3.4 on our Shared plans. You are receiving this email because you have one or more mLab deployments in the "radgrad" mLab account that will be affected by upcoming maintenance.

On Tuesday May 7, 2019, we will start a three-day maintenance window to upgrade all Shared plan deployments running MongoDB 3.4 to MongoDB 3.6. Sandbox and Dedicated plan deployments will not be impacted.

Key details about this maintenance window

This three-day maintenance window starts Tuesday, May 7 at 10:00 am PDT / 5:00 pm UTC (convert to your timezone).
Shared Single-node plan databases will be unavailable for approximately five minutes at some point during this three-day window. Highly-available Shared Cluster plan databases will experience no downtime from this maintenance, just failovers.
You must ensure that your Shared plan databases running 3.4 meet the upgrade requirements for 3.6. As part of this process if you need to upgrade your driver version we recommend upgrading to a 4.0-compatible driver instead of just a 3.6-compatible driver.
No other configuration changes will be necessary on your end.
Impacted deployments in the "radgrad" mLab account

Shared plan deployments currently running 3.4:

ds125900 (radgrad-paid) - running 3.4.19
How to avoid this maintenance window

We highly recommend that you self-service the upgrade to version 3.6 prior to the auto-upgrades scheduled to begin on May 7, 2019 so that you are in control of the process and timing.

If you’d like to stay on 3.4, you can change to a Dedicated plan running 3.4 prior to the event (see Dedicated plan pricing). You may also submit a one-time extension request to June 7, 2019 by replying to this notification (support@mlab.com).

Additional help

As always, contact us anytime at support@mlab.com with any questions, issues, or feedback.

Best regards,
mLab Operations

**Comment by philipmjohnson** [comment]
Relevent link:
* https://docs.mlab.com/ops/#change-version

Just received this reminder email today:

Hello from mLab,

We are writing to remind you that we are discontinuing support for MongoDB 3.4 on our Shared plans. You are receiving this email because you have one or more mLab deployments in the "radgrad" mLab account that will be affected by upcoming maintenance.

On Tuesday May 7, 2019, we will start a three-day maintenance window to upgrade all Shared plan deployments running MongoDB 3.4 to MongoDB 3.6. Sandbox and Dedicated plan deployments will not be impacted.

Key details about this maintenance window

This three-day maintenance window starts Tuesday, May 7 at 10:00 am PDT / 5:00 pm UTC (convert to your timezone).
Shared Single-node plan databases will be unavailable for approximately five minutes at some point during this three-day window. Highly-available Shared Cluster plan databases will experience no downtime from this maintenance, just failovers.
You must ensure that your Shared plan databases running 3.4 meet the upgrade requirements for 3.6. As part of this process if you need to upgrade your driver version we recommend upgrading to a 4.0-compatible driver instead of just a 3.6-compatible driver.
No other configuration changes will be necessary on your end.
Impacted deployments in the "radgrad" mLab account

Shared plan deployments currently running 3.4:

ds125900 (radgrad-paid) - running 3.4.19
How to avoid this maintenance window

We highly recommend that you self-service the upgrade to version 3.6 prior to the auto-upgrades scheduled to begin on May 7, 2019 so that you are in control of the process and timing.

If you’d like to stay on 3.4, you can change to a Dedicated plan running 3.4 prior to the event (see Dedicated plan pricing). You may also submit a one-time extension request to June 7, 2019 by replying to this notification (support@mlab.com).

Additional help

As always, contact us anytime at support@mlab.com with any questions, issues, or feedback.

Best regards,
mLab Operations

**Comment by cammoore** [comment]
Upgraded to 3.6.
