### ISSUE TITLE
Improve advisor filtering 

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#299]
Please do work for this task in a branch called issue-299.

Gerald has problems with the current filtering mechanism.  One design idea:

* Make the filter button pop up a dialog window with first name, last name, and email fields.
* Use on change to do filtering each time Gerald types.
* Only start displaying items when there are less than (say) 30. Otherwise just say "200 matches" or something. 
* Clicking on a tile both exits the dialog window and displays the results (and scrolls to that part of the screen). 
* Also a cancel button

**Comment by cammoore** [comment]
Admin Filter User widget isn't working on master.

**Comment by cammoore** [comment]
Fixed, need a review.

**Comment by cammoore** [comment]
Updated select student display.
