### ISSUE TITLE
Evaluate advisor pages layout on portrait monitor

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#301]
Please do work for this task in a branch called issue-301.

Gerald uses a portrait monitor to display RadGrad pages.  I noticed on 4/16/19 that some page layouts were suboptimal on a portrait monitor.  

For this issue, determine the dimensions of Gerald's monitor, and then evaluate all of the advisor pages with the screen sized to those dimensions.  

Fix layouts that do not display well on a portrait monitor.

**Comment by cammoore** [comment]
Pending verification request doesn't look good in portrait mode. The status overlaps with the decline button.

**Comment by cammoore** [comment]
Updated all the Advisor pages to support portrait mode.
