### ISSUE TITLE
Opt-in sharing of personal information (FERPA compliance)

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#302]
Please do work for this task in a branch called issue-302.

FERPA regulations strictly limits the kinds of information that can be disclosed about students. Yet RadGrad can be more effective as a community building mechanism if some information is disclosed.  

To address this issue, we can make disclosure of personal information "opt-in".  For example, there can be a special area of the profile page that is delineated as "Optional" profile information: students can decide (or not) to share things like:

  * Profile picture
  * Email address
  * Professional portfolio page
  * Interests, Career Goals, Degree Plan
  * Opportunities and Courses taken

(If we do this, then we cannot make adding a profile picture a requirement to reach Level 4!)

**Comment by cammoore** [comment]
Do we share their level and ICE?

**Comment by philipmjohnson** [comment]
Sure, it could be opt-in

**Comment by cammoore** [comment]
Do you have time to talk tomorrow? This is a big hard problem.

**Comment by philipmjohnson** [comment]
yes, will be in around noon.

**Comment by cammoore** [comment]
Need to make all pictures in Feeds etc check to see if the student has opted-in before showing their picture. Might also need to do this in other collections. May need to be able to check if a picture is a student's picture.

**Comment by cammoore** [comment]
Fixed the feed's picture problem with a function that checks if the first userID is sharing their picture otherwise it uses the default-profile-picture.png.

**Comment by cammoore** [comment]
Looks like CourseInstance and OpportunityInstance publications are broken. Students don't get other students' instances. This makes the recommended opportunities and courses interested students not work.

**Comment by cammoore** [comment]
Student_User_Card is not responsive when the student changes their sharing information.

**Comment by cammoore** [comment]
Fixed most of the issues and pushed to master as a part of #288. Should have a review before deploying to Galaxy.

**Comment by cammoore** [comment]
Forgot about the SlugCollection :(

**Comment by cammoore** [comment]
Not publishing StudentProfile slugs. Seems to work
