### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#307]
Please do work for this task in a branch called issue-304 (if necessary).

```
From: Information and Computer Sciences <icsinfo@hawaii.edu>
Date: Tue, Jun 18, 2019 at 1:50 PM
Subject: RadGrad Site
To: Johnson, Philip <johnson@hawaii.edu>
```

Hi Philip,
I've been working on our ICS Department website and updating it, so I spent a little bit of time on the radgrad.ics.hawaii.edu site as well. I noticed a few links that were broken or out of date that my WordPress account did not have access to, so Scott referred me to you. The links I found are:

On  https://radgrad.ics.hawaii.edu/ there are two links referring to the 67 interests or interest areas that refer to a specific interest (dotNet, at https://radgrad.ics.hawaii.edu/explorer/interests/dotNet) which might be better to change to the general interests page (https://radgrad.ics.hawaii.edu/explorer/interests/)

The contact link at the bottom of  https://radgrad.ics.hawaii.edu/  has a link to https://www.radgrad.org/organization/contact.html. However this is a broken link, and it should be  https://www.radgrad.org/contact-us.html . 

This is also true for each of the guided tour pages ( https://radgrad.ics.hawaii.edu/guidedtour/student and https://radgrad.ics.hawaii.edu/guidedtour/advisor and  https://radgrad.ics.hawaii.edu/guidedtour/faculty and https://radgrad.ics.hawaii.edu/guidedtour/mentor )

**Comment by cammoore** [comment]
Done
