### ISSUE TITLE
Delete opportunity broken, messes up ICE

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#308]
Please do work for this task in a branch called issue-308.

Trying to delete an opportunity in Sample Student in Galaxy appears broken; opportunity does not get deleted and the ICE calculation breaks (empty circles in dashboard):

<img width="1520" alt="Screen Shot 2019-06-24 at 1 08 15 PM" src="https://user-images.githubusercontent.com/290288/60057755-6884ec00-9681-11e9-8d30-5fea3b3d5707.png">

**Comment by cammoore** [comment]
I don't get that behavior but am fixing some other issues.
