### ISSUE TITLE
Add new student in advisor mode busted

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#309]
Please do work for this task in a branch called issue-309.

See this:

<img width="1520" alt="Screen Shot 2019-06-24 at 1 28 37 PM" src="https://user-images.githubusercontent.com/290288/60058604-bcdd9b00-9684-11e9-8c06-5ed4c718e22b.png">

**Comment by cammoore** [comment]
Can't reproduce this locally.

**Comment by cammoore** [comment]
Had a race condition on the Feed defineMethod call. Eliminated the race condition by only defining Feed instances on the Server.
