### ISSUE TITLE
Improve course scoreboard

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#311]
Please do work for this task in a branch called issue-311.

- [x] Would be good to limit the display to the upcoming 9 semesters (three years). Data beyond that is probably not useful.
- [ ] Students are planning courses that will not be offered (i.e  471.)  What to do about that?
- [x] Make it a table so we can scroll rows and still see column header.
- [ ] 451 and 461: some semesters have clearly more students, would be good to get them to agree on a single semester.
- [x] Maybe make a csv output button.

**Comment by cammoore** [comment]
Fixed most of the issues and pushed to master
