### ISSUE TITLE
Improve RadGrad page load times (for students)

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#313]
Please do work for this task in a branch called issue-313.

As a student, RadGrad pages load too slowly.  We need to look at the subscriptions and make sure that students don't load an excessive number of (say) course instances. 

This might eliminate some functionality, at least temporarily, such as faces for courses.

**Comment by cammoore** [comment]
* [ ] Students participating in career goals
* [ ] Retire BS CE
* [ ] Students participating in interests
