### ISSUE TITLE
Improve RadGrad page load times (for advisors)

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#314]
Please do work for this task in a branch called issue-314.

It occurs to me that we should also monitor and redesign that advisor role so that Gerald is not paying the cost of loading all course and opportunity instances each time he brings up RadGrad.  

I think it should be possible to not subscribe to any course or opportunity instances by default, and only do this subscription once Gerald goes to the student's degree plan page. 

I hypothesize that this will make page load times way, way faster for Gerald, and the overhead of retrieving a single student's set of course and opportunity instances should be negligible.

**Comment by cammoore** [comment]
Is ~5 seconds fast enough?

**Comment by cammoore** [comment]
Now only load course and opportunity instances when visiting student pages.
