### ISSUE TITLE
Redesign scoreboard to prevent container overflow

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#324]
Please do work for this task in a branch called issue-324.

The future enrollment widget widget overflows its container in both the Explorer page and the Degree Planner page:

![Screen Shot 2019-08-11 at 8 21 50 AM](https://user-images.githubusercontent.com/290288/62837942-4df6da00-bc11-11e9-84da-1be66224feea.png)

Potential solution: Reimplement this widget as a grid with two rows rather than as a table.

**Comment by cammoore** [comment]
Fixed in #328
