### ISSUE TITLE
Make selected Academic Plan sticky

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#327]
Please do work for this task in a branch called issue-327.

Once you leave the Academic Plan tab and return to it, your prior selection is lost and you get the pull-down menu.

**Comment by cammoore** [comment]
This only happens if you cause a reload of the page since the value is stored in a ReactiveVar. I've made the View in Explorer links open a new tab so we don't have to reload the degree planner page and lose the selected plan.
