### ISSUE TITLE
Fix CSS for Degree Planner "Inspection" Tabbed Pane

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#328]
Please do work for this task in a branch called issue-328.

The Degree Planner Opps/Plans/Courses/Details widget looks great until you resize it, then it don't look so good anymore:

<img width="481" alt="Screen Shot 2019-08-13 at 1 21 28 PM" src="https://user-images.githubusercontent.com/290288/62984096-893e0800-bdcd-11e9-9e08-2e980e0563a3.png">

Two problems as illustrated by the above screen shot:

1. The tabbed menu moves off the enclosing widget boundary.
2. The interior box and scrollbars are wonky: they don't fill up the interior area.

**Comment by philipmjohnson** [comment]
Here's another couple of issues:

<img width="413" alt="Screen Shot 2019-08-13 at 1 42 54 PM" src="https://user-images.githubusercontent.com/290288/62984844-6bbe6d80-bdd0-11e9-8104-86f3bf51ddb2.png">

1. The future enrollment goes outside the box.
2. I am questioning the need for the "Remove from Plan" button. Isn't this redundant? Can't the students just use the X button in the degree planner window?

**Comment by philipmjohnson** [comment]
I feel like Mercedez had some reason for having that button, but I can't remember.

**Comment by cammoore** [comment]
For courses, the button might be redundant. For opportunities it isn't you should be able to remove a past opportunity if you never did it.

**Comment by cammoore** [comment]
Fixed the future enrollment widget and the tabs are much smaller so they don't run outside the box as much.
