### ISSUE TITLE
Verification requests should include a "Documentation" text string

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#329]
Please do work for this task in a branch called issue-329.

I got a verification request from a student and realized I didn't know what they had done, and furthermore there was no way for them to communicate this to me within the system. I think there needs to be a "Documentation" text field that appears with the "Request Verification" button that provides the ability for the student to explain what they did, unlike the current situation:

<img width="1386" alt="Screen Shot 2019-08-14 at 2 04 40 PM" src="https://user-images.githubusercontent.com/290288/63064471-e654bf00-be9c-11e9-9d7f-3016b2d8a86d.png">

Then, it should be possible for me to "Decline" a verification request with a request for more specific info, and if so, the Details should revert to request verification with the text field that allows them to provide more.  Does that make sense

**Comment by cammoore** [comment]
When a verification request is declined, the student should be able to request verification again. This will not create a new verification request, but change the status to Open with new documentation string.  Maybe, append to the documentation string.
