### ISSUE TITLE
Teaser update code broken

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#331]
Please do work for this task in a branch called issue-331.

After adding the entity type to the pull down menu, updates are broken. See console:

<img width="1514" alt="Screen Shot 2019-08-20 at 11 01 52 AM" src="https://user-images.githubusercontent.com/290288/63384186-0f140300-c33a-11e9-8119-88339930e2cb.png">

**Comment by cammoore** [comment]
Fixed
