### ISSUE TITLE
Filter Target Slug list in Add Teaser Form

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#332]
Please do work for this task in a branch called issue-332.

There are a lot of slugs listed in the "Target Slug" dropdown in the Add Teaser form. Not all of them, at this time, will have teasers.

To make Teaser addition easier, please only show the slugs for Opportunities and Courses. Please list all Opportunities (in alphabetical order) first, then all Courses (also in alpha order). 

In the unlikely event that we ever develop teasers for other entities, we can add in additional classes of entities.

**Comment by philipmjohnson** [comment]
OK, spoke too soon. Looks like we have a bunch of teasers for Career Goals, and let's assume we'll get them for Interests as well. So, please:

1. Add Career Goals and Interests to the pull-down list in the Add/Edit Teaser forms.
2. Make sure that the details pages for Career Goals and Interests will display the teaser, if present.

**Comment by cammoore** [comment]
Only non-retired are shown.
