### ISSUE TITLE
Booz Allen Teaser does not display

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#334]
Please do work for this task in a branch called issue-334.

For some reason, the Booz-Allen teaser does not display, even though the YouTube ID is correct. I wonder if there is some issue with an escaped character or something? 

Here's the Teaser Page (video is blacked out and doesn't work when you click it):

https://radgrad.ics.hawaii.edu/explorer/opportunities/booz-allen-internship

Here's the YouTube video (which plays fine when you access it directly):

https://www.youtube.com/watch?v=-cB39-0t-Qw

**Comment by cammoore** [comment]
Updated the landing explorers to support teasers.
