### ISSUE TITLE
Make Level Criteria Explicit.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#336]
Please do work for this task in a branch called issue-336.

Tasks:

* All properties must be available in the settings file. 
* Settings file structure is fixed.
* Setting a property to zero means any value is acceptable at that level.
* Update Level Calculation function to use only the settings. 
* Support generation of a string that specifies the criteria for achieving a level.
* Put this string in the ICE Points page as well as in the recommendation function.

**Comment by cammoore** [comment]
Have markdown level criteria in Student Levels page and Recommendations and Warnings.
