### ISSUE TITLE
Reopening Verification Request does not reset completed flag

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#338]
Please do work for this task in a branch called issue-338.

If an Opportunity is verified, and then the Verification is "re-opened" later, the Opportunity continues to be listed on the page as completed.

Proposed behavior:  When an advisor re-opens a verification request, the opportunity should be reverted to non-verified status, which means:
* It should be deletable in the Explorer.
* The earned points should be deducted.
* The checkmark in the tooltip should become a question mark.

**Comment by cammoore** [comment]
fixed in #339
