### ISSUE TITLE
Implement login and roles

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#34]
* Implement CAS authentication (see http://ics-software-engineering.github.io/meteor-example-uh-cas/)
* Define radgrad@hawaii.edu as an admin.
* Define fake hawaii.edu accounts for our fixture datasets.
* Everyone will login to the system as radgrad@hawaii.edu (I will provide the password in a meeting).
* Once logged in as an admin, the user can select a student account for data display from the admin home page. 
* After entering the student account and submitting the form, the system will now display four top-level menus: two for the Admin, and below that, two for the user. The admin can now display any of the pages from the student perspective by clicking on the student menu links. 
* (Advanced) Four menus take up space. It would be cool to have a toggle associated with the menus that allows the user to hide either the student menus or the admin menus. But that can be a later step.

**Comment by cammoore** [comment]
Sorta, kinda can do it now. The admin can select the Student, Advisor, Faculty, and Mentor they want to be when they view the other pages.

**Comment by cammoore** [comment]
The admin part is done.

**Comment by cammoore** [comment]
Advisor is done. Going to switch back to Meteor logins.
* Need to figure out how to add login hooks so we can redirect to the right pages and set up the SessionState on login.

**Comment by cammoore** [comment]
Done.
