### ISSUE TITLE
Make filters sticky in Explorer

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#341]
Please do work for this task in a branch called issue-341.

I was working with a student and switching back and forth between the explorer and the degree planner page. 

It was frustrating to have to reset the filter every single time we returned to the explorer. 

Please make filters sticky. 

Stretch goal: return to the same place in the scrolled list.  But that might be hard.

**Comment by cammoore** [comment]
Storing the information in the BaseProfile.
