### ISSUE TITLE
Update Newsletter text for how to verify opportunities

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#342]
Please do work for this task in a branch called issue-342.

This text needs to be updated:

<img width="759" alt="Screen Shot 2019-09-10 at 5 06 29 PM" src="https://user-images.githubusercontent.com/290288/64888649-37c0ad00-d607-11e9-8a16-3bf78d8f66c1.png">

**Comment by cammoore** [comment]
Updated messages.
