### ISSUE TITLE
Public Course Explorer is broken

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#346]
Please do work for this task in a branch called issue-346.

The public course explorer is broken. This bug does not occur under all situations. To reproduce, I can follow these steps:

1. Open a new incognito window.
2. Navigate to public course explorer: https://radgrad.ics.hawaii.edu/explorer/opportunities
3. Select Course Explorer from left menu.
4. Scroll down and click "View More" for ICS 361.  

While the URL will change to the ICS 361 page, nothing will change in the window, the pull-down menu to select an explorer will no longer work, and there will be errors in the console. Here's a screen shot:

![Screen Shot 2019-09-25 at 10 08 15 AM](https://user-images.githubusercontent.com/290288/65635820-cb399c80-df7c-11e9-9d91-f2f18f28da42.png)

**Comment by philipmjohnson** [comment]
Here's the APM page for this time period listing errors:

![Screen Shot 2019-09-25 at 10 15 03 AM](https://user-images.githubusercontent.com/290288/65636134-6c285780-df7d-11e9-8438-3b2fcfa66695.png)

**Comment by philipmjohnson** [comment]
Note that I just added a Teaser to ICS 361.  Some of the other courses look OK.  Is this a problem?

**Comment by cammoore** [comment]
Not sure what the issue was. The thing that killed the page was the {{#each}} not getting what it needed.

Can't reproduce locally so it is fixed.

**Comment by cammoore** [comment]
Turns out the Landing_Course_Explorer_Widget doesn't work for courses with Teasers.

**Comment by cammoore** [comment]
Cleaned up the explorer. It now works for courses with and without teasers.
