### ISSUE TITLE
Create Advisor Log

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#35]
* Do work for this issue in a branch called issue-35
* Ideally this is a template that can be used without change in both student and advisor views
* Both student and advisor views should contain a log of meetings:
* Logs are just strings.
* Backed by a timestamped collection with the student ID and advisor ID.
* See the mockup evaluation design for usage.

**Comment by cammoore** [comment]
Need further discussion about this feature. In another issue. Done for now
