### ISSUE TITLE
Create Degree Plan Template generator

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#36]
* Do work for this issue in a branch called issue-36
* Pressing the degree plan generator button should produce a plausible degree plan.
* Start by checking to see that the student's degree plan has no ICS courses in it.  If there are any, indicate the system requires an empty degree plan. As the system progresses, relax the constraint on what the degree plan generator can handle.
* Should require knowledge of the student's degree program. 
* Might or might not require interests and/or career goals to be specified. 
* The degree plan should: (a) satisfy CS requirements for the degree; (b) get to 100/100/100 in ICE.

**Comment by cammoore** [comment]
Need to scale the Competency for A's and B's.

**Comment by cammoore** [comment]
Need smarter opportunity selector. Use the type of the opportunity. In the first year shouldn't have Research or Internship.

**Comment by cammoore** [comment]
Now only allow Events and Clubs during the first year.

**Comment by cammoore** [comment]
The course choices for the 3xx and 4xx don't consider prerequisites. So we generate plans that are invalid.

**Comment by cammoore** [comment]
How are we going to handle STAR data.  We really don't have access to the client file system. We might need to upload the STAR file then process on the server. Need to talk about this.

**Comment by philipmjohnson** [comment]
Advisors (and me) have access to STAR data. Advisors can login to STAR, download the data to the local file system as a CSV file, and then (inside RadGrad) upload the CSV and process. Does that answer your question?

**Comment by cammoore** [comment]
Fixed the STAR upload. The plan generator takes into account the passed ICS courses and generates a 'valid' plan.
