### ISSUE TITLE
Improve ICE Page formatting

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#44]
* Please do work for this issue in a branch called issue-44.
* Explore better formatting for the ICE page; maybe try accordion style layout.

![ice-page-layout](https://cloud.githubusercontent.com/assets/290288/20855614/64843304-b8a3-11e6-924a-549f4bdcf1aa.png)

**Comment by amymalia** [comment]
Latest version of ICE segment before closing issue. 
<img width="983" alt="screen shot 2016-12-08 at 11 31 11 pm" src="https://cloud.githubusercontent.com/assets/2596254/21044176/ae9a6620-bd9e-11e6-942a-3ea96e3198bd.png">
