### ISSUE TITLE
Remove session state

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#52]
* Please do work for this issue in a branch issue-52.
* Delete the file imports/startup/client/session-state.js.
* Delete ui/components/admin/advisor-selector, faculty-selector, mentor-selector, session-state-segment.
* Delete ui/components/shared/student-selector
* Delete api/admin and api/advisor directories.
* Delete ui/layouts/shared/advisor-utilities
* Then search for remaining occurrences of SessionState, and:
  * Delete the imports.
  * Delete all references to `SessionState` or `updateSessionState()`;

To get the userID from the URL, do the following:

```
import { Users } from '../../../api/user/UserCollection.js';
import { FlowRouter } from 'meteor/kadira:flow-router';
  :
  :
Users.findDoc({ username: FlowRouter.getParam('username') })._id;
```

Also see [route-user-name.js](https://github.com/radgrad/radgrad/blob/master/app/imports/ui/components/shared/route-user-name.js) for helpers.

**Comment by cammoore** [comment]
Removed SessionState from everything.
Removed the selectors.
Kept the student-selector, will replace when we redesign the Advisor Page.
Removed the Admin and Advisor Choice collections and directories.
Kept the sessionKeys imports and definitions.
Created getUserIdFromRoute function in /imports/ui/components/shared/get-user-id-from-route.js.
