### ISSUE TITLE
Investigate performance of Student Degree Planner Page.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad#55]
Why does it take 4 seconds to change a planned grade?

**Comment by cammoore** [comment]
Looks like the issue is with the DDP update that can take a while.

**Comment by philipmjohnson** [comment]
I am wondering if the issue is that we are not using Methods to update the DB.  Recall that Meteor has latency compensation to make DB updates very fast.  Might be worth converting to methods to make sure that isn't the source of the problem.

**Comment by philipmjohnson** [comment]
Next step: create a video to document problem, post to Meteor Forums.
