### ISSUE TITLE
Improve degree planner design

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#60]
Please do work for this issue in a branch named issue-60.
I was looking at the degree planner layout today, and came up with this idea about how to improve it:

![revised-degree-planner-layout](https://cloud.githubusercontent.com/assets/290288/21584461/eafd1052-d04c-11e6-8d9b-98c59aa66fac.jpg)

First, here are the things I personally find confusing in the current design: (1) There are too many interior structures, and the background gray color inside the semester box along with the red line all make it very difficult to understand the structure. (2) It's not clear why credit hours is included. (3) Having the "add" button in the degree planner but the "delete" button in the inspector window is non-symmetric.

So, I drew up a new design to address these issues: (1) I got rid of the "AY 2015-2016" type titles entirely. Instead, each widget states the year ("FALL 2016").  The academic year is implied structurally: each column represents an academic year.  (2) Once each semester indicates its associated year, there's no need for the "outer" box for an academic year.  So, a column just contains three "semester" widgets, along with a little padding so that the gray background color comes through. The interior of a semester widget is all white. (3) I removed credit hours, since we don't use that information, and added a delete "x" to any entry that can be deleted. Thus, add and delete are both present in the same area of the UI. (4) I changed the "+" button to an "Add" button and moved it to the bottom of the widget. This makes the UI more similar to other widgets.  (5) I got rid of the "..." option. Instead, you can only select A, B, or C as your projected grade. (Default to B).

Amy adds that it would be nice to highlight the current semester. Options: new background color, new outline color, or simply provide a different color for the title.

**Comment by philipmjohnson** [comment]
Just had another idea: could you move the "add new academic year" button from below the entire plan to the inside of the final summer semester shown?  That would save some space while still making sense: it's at the "end" of the degree plan. You can label it "Add Year", that should be sufficient.

I think you can also get rid of the "Projected ICE" widget entirely, now that the ICE stuff appears in the header.

Finally, what about disabling or removing the "Add" button from past semesters when the logged in user is a student? 99% of the time the student shouldn't be able to update a past semester.  In the cases that he does, then we can say he needs to go see an Advisor and the advisor can display the page which will have the Add button enabled.

**Comment by philipmjohnson** [comment]
OK, another proposal: reduce the vertical size of the "inspector" and move the recommendations and warnings panels underneath it?  I am worried that most students won't even see them the way the page is laid out now.  It also seems like very few courses/opportunities use up that entire space.

**Comment by philipmjohnson** [comment]
Sorry for having all these ideas all of a sudden.

In the popup with the hierarchical listing of courses and opportunities, for courses, instead of just listing the course number, could you add the "short name"? I think that will add value to students who won't have a clue what "ICS 471" means.

**Comment by cammoore** [comment]
A much better layout. The past is fixed and cannot be changed by the student.
