### ISSUE TITLE
Update Advisor page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#64]
Please do all work for this issue in a branch called issue-64.

Update the Advisor page to be compatible with the latest thinking about that workflow.

**Comment by cammoore** [comment]
I'll get the generate degree plan working with the new DesiredDegreeCollection IDs vs Strings.
Not sure about the latest thinking about workflow.

**Comment by cammoore** [comment]
Done with the desiredDegreeID updates.
