### ISSUE TITLE
Implement recommendations and warnings

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#70]
Please do all work for this issue in a branch called issue-70.

The goal of this issue is to create a mechanism whereby the system dynamically generates recommendations and warnings when:
* The student makes changes to their degree plan;
* An advisor/admin makes changes to the set of courses, opportunities, interests, or career goals in the system.

We implement this through "feedback functions" and "feedback triggers". A feedback trigger is invoked when something changes in the system:
* The set of interests changes
* There is a new semester
* The student has modified their course instances.

The feedback trigger is responsible for:
* Removing any old feedbacks (recommendations or warnings) it created
* Generating a fresh set of feedbacks based upon the new state of the user. This is accomplished by running the "feedback function" associated with the trigger.

Since this involves a lot of dynamic recomputation, it might be preferable to create "local collections" (i.e. collections that are not stored on the server but exist only in the client) to store the set of recommendations and warnings, and regenerate them each time the user visits the degree planner page. 

Here are a couple of pages from my design book documenting my approach:

![img_1385](https://cloud.githubusercontent.com/assets/290288/21789806/cd2d14ca-d67b-11e6-8394-a1ef0f18a58c.jpg)

![img_1386](https://cloud.githubusercontent.com/assets/290288/21789801/c12897a8-d67b-11e6-94c5-a89fa426a285.jpg)

**Comment by cammoore** [comment]
For the missing courses, do we want to detect what semester the student should be taking that course?  Could be difficult.

**Comment by philipmjohnson** [comment]
Too hard, let the student and advisor figure it out.
