### ISSUE TITLE
Polish advisor page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#77]
Please do work for this issue in a branch called issue-77.

Polish the advisor page prior to mockup evaluation.
* Consider allowing advisor to select student using the tab approach in the [advisor home page](http://radgrad.meteorapp.com/admin/radgrad/home). That way, all known students are displayed; the advisor doesn't have to type some characters correctly to find them.
* Help panels for all pages with useful text.
* Feedback after pushing the generate degree plan button, no link back to the student's plan

**Comment by cammoore** [comment]
Still need to update the Help.
