### ISSUE TITLE
Provide image files for all users

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#79]
Please do all work for this issue in a branch called issue-79.

* Create a public/images/people directory.
* Add square headshots of all students and faculty to this directory.
* Update the user's picture field to point to their headshot.
* Philip will update ics-portfolios in the next 24 hours so that there is access to headshots for course review users.
* Use the users slug to name the image file.  (i.e. johnson.png)

**Comment by amymalia** [comment]
All student and faculty images have been added to public/images/people
