### ISSUE TITLE
Implement levels

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad#83]
Please do all work for this issue in a branch called issue-83.

The following Slack post discusses the motivation for levels and a preliminary design:
https://slack-files.com/T0CDM58GP-F3LML0J1L-c200113578

Review and revise this design, and provide implementation.

**Comment by cammoore** [comment]
Have provided three Meteor Methods, calcLevel, updateStudentLevel and updateAllStudentLevels. These methods are based upon the design deferring the mentorspace participation. See /import/api/level/LevelProcessorMethods.js for the names of the methods.

Added a button to the admin student page to update all the students' levels.  When the advisor loads STAR data the system updates that student's level automatically.
